# Generated by Django 6.0 on 2026-07-25 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_type', models.CharField(default='Official Transcript', max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_official', models.BooleanField(default=False)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registrar_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dean_name', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='students.student')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
