# Generated by Django 6.0 on 2026-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_alter_transcript_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='verification_code',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
