# Generated by Django 6.0 on 2026-07-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Example: 2026/2027', max_length=20)),
                ('semester', models.CharField(help_text='Example: First Semester', max_length=20)),
                ('total_credit_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_quality_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gpa_records', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', 'semester'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year', 'semester'), name='unique_student_gpa_period')],
            },
        ),
    ]
