# Generated by Django 6.0 on 2026-08-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('registrations', '0002_registration_course'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'academic_year', 'semester'), name='unique_student_course_registration'),
        ),
    ]
